export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";
export const INCREMENT_BY_TEN = "INCREMENT_BY_TEN";
export const DECREMENT_BY_TEN = "DECREMENT_BY_TEN";
export const UPDATE_BY_VALUE_INCREMENT="UPDATE_BY_VALUE_INCREMENT"
export const UPDATE_BY_VALUE_DECREMENT="UPDATE_BY_VALUE_DECREMENT"